import type { Metadata } from "next";
import DashboardNavbar from "@/components/dashboard-navbar";
import { AppSidebar } from "@/components/dashboard-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import "@/app/styles/globals.css";

export const metadata: Metadata = {
  title: "Ngarembug - Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="[--header-height:calc(--spacing(14))]">
      <SidebarProvider className="flex flex-col">
        <DashboardNavbar />
        <div className="flex flex-1 overflow-hidden">
          <AppSidebar />
          <SidebarInset>
            <div className="flex flex-col flex-1 p-4 md:p-8 lg:p-10 min-h-0 min-w-0">
              {children}
            </div>
            <Toaster richColors theme="light" />
          </SidebarInset>
        </div>
      </SidebarProvider>
    </div>
  );
}
